services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 27017:3306
    expose:
      - 3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./apps/api/src/app/core/database/database-init.sql:/data/application/init.sql
      - local-shelf-db:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: 'Localdr0p1234'
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  api:
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: ./api.Dockerfile
    image: local-shelf-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 49992:3333
    environment:
      - APP_ENV=development
      - DB_USER_ADMIN=root
      - DB_PASS_ADMIN=Localdr0p1234
      - DB_USER=localdrop
      - DB_PASS=Localdr0p1234
      - DB_HOST=db
      - DB_PORT=3306
      - JWT_SECRET=secret
      - NODE_ENV=development
      - VERIFY_EMAIL_BASE_URL=http://localhost:4200/verify-email
volumes:
  local-shelf-db: {}
